import Head from "next/head";

import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";

import styles from "@/styles/Home.module.css";

import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import ss1 from '../public/ss1.png';
import ss3 from '../public/ss3.png';
import ss7 from '../public/ss7.png';
import t2 from '../public/t2.png';
import t3 from '../public/t3.png';
import t4 from '../public/t4.png';
import { useState } from "react";
import chibi1 from "../public/chibi1.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Tayfun Şener Portfolio</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-2xl font-burtons dark:text-white rounded-full cursor-pointer">Tayfo10</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:bg-gray-900 dark:text-white "
                />
              </li>
              <li>
                <a
                  className="bg-cyan-500  text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Tayfun Şener
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              Providing services for programming and designing. Join
              me down below and let's get started.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://github.com/Tayfo10" target='_blank'>
              <AiFillGithub className=" cursor-pointer  dark:bg-gray-900 dark:text-white" />
            </a>
            <a href="https://www.linkedin.com/in/tayfunsener/" target='_blank'>
              <AiFillLinkedin className="cursor-pointer  dark:bg-gray-900 dark:text-white" />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={chibi1} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-5xl py-1 mt-20 dark:text-white">Services</h3>
            <p className="text-md mt-4 py-2 leading-8 text-gray-800 dark:text-white">
            As a front-end developer, I can offer a variety of services to clients looking for a professional and reliable web development partner. I have experience in HTML, CSS, and JavaScript, and can provide support in creating and maintaining responsive and visually appealing websites. I am also well-versed in using frameworks such as React and Next to build dynamic user interfaces.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
            Additionally, I can assist with website optimization, ensuring that your website is fast-loading and user-friendly. With my strong attention to detail and problem-solving skills, I am confident in delivering high-quality results that meet your specific needs and requirements.
            </p>
          </div>

          <div className=" lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 w-96 h-80 mt-16 dark:bg-white">
              <Image
                src={design}
                width={100}
                height={100}
                alt="3d-logo"
                className="mx-auto"
              />
              <h3 className="text-lg font-medium text-teal-600 pt-8 pb-2">
                Beautiful Design
              </h3>
              <p className="py-2">
                 Elegant design suited to needs
              </p>
              <h4 className="py-4 text-teal-600"></h4>
              <p className="text-gray-800 py-1"></p>
              <p className="text-gray-800 py-1"></p>
              <p className="text-gray-800 py-1"></p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 w-96 h-80 mt-16 dark:bg-white">
              <Image
                src={code}
                width={100}
                height={100}
                alt="3d-logo"
                className="mx-auto"
              />
              <h3 className="text-lg text-teal-600 font-medium pt-8 pb-2">
                Clean Code
              </h3>
              <p className="py-2">
                Easy to read, maintain, and scale
              </p>
              <h4 className="py-4 text-teal-600"></h4>
              <p className="text-gray-800 py-1"></p>
              <p className="text-gray-800 py-1"></p>
              <p className="text-gray-800 py-1"></p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 w-96 h-80 mt-16 dark:bg-white">
              <Image
                src={consulting}
                width={100}
                height={100}
                alt="3d-logo"
                className="mx-auto"
              />
              <h3 className="text-lg font-medium text-teal-600 pt-8 pb-2">
                Expert Consulting
              </h3>
              <p className="py-2">
              Tailored to your specific coding needs
              </p>
              <h4 className="py-4 text-teal-600"></h4>
              <p className="text-gray-800 py-1"></p>
              <p className="text-gray-800 py-1"></p>
              <p className="text-gray-800 py-1"></p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-5xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
            Explore my coding portfolio and discover a showcase of my skills, experience, and passion for creating efficient and innovative solutions.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={ss1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={t2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={ss3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={t3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={ss7}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={t4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
